<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Harbor</AssemblyName>
    <RootNamespace>Harbor</RootNamespace>
    <Version>0.6.0-preview</Version>
    <ApplicationIcon>Assets/harbor.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="YamlDotNet" Version="18.1.0" /></ItemGroup>
  <ItemGroup><Resource Include="Assets/*.ico"/><Resource Include="Assets/harbor.png"/></ItemGroup>
</Project>
